### ISSUE TITLE
Error: illegal operands addi sp,sp,-5024 (and more)

### ISSUE THREAD

**Issue by rwmjones** [nojb/riscv-ocaml#2]
A few more "illegal operands" errors:
```
/tmp/camlasmc5d6d1.s:28690: Error: illegal operands `addi sp,sp,-5024'
/tmp/camlasmc5d6d1.s:28691: Error: illegal operands `sd ra,5016(sp)'
/tmp/camlasmc5d6d1.s:28693: Error: illegal operands `sd a0,5008(sp)'
/tmp/camlasmc5d6d1.s:28697: Error: illegal operands `sd a0,5000(sp)'
/tmp/camlasmc5d6d1.s:28699: Error: illegal operands `ld a0,5008(sp)'
/tmp/camlasmc5d6d1.s:28703: Error: illegal operands `sd a3,4992(sp)'
/tmp/camlasmc5d6d1.s:28705: Error: illegal operands `sd a4,4984(sp)'
/tmp/camlasmc5d6d1.s:28707: Error: illegal operands `sd a5,4976(sp)'
/tmp/camlasmc5d6d1.s:28709: Error: illegal operands `sd a6,4968(sp)'
/tmp/camlasmc5d6d1.s:28711: Error: illegal operands `sd a7,4960(sp)'
/tmp/camlasmc5d6d1.s:28713: Error: illegal operands `sd s2,4952(sp)'
/tmp/camlasmc5d6d1.s:28715: Error: illegal operands `sd s3,4944(sp)'
/tmp/camlasmc5d6d1.s:28717: Error: illegal operands `sd s4,4936(sp)'
/tmp/camlasmc5d6d1.s:28719: Error: illegal operands `sd s5,4928(sp)'
/tmp/camlasmc5d6d1.s:28721: Error: illegal operands `sd s6,4920(sp)'
/tmp/camlasmc5d6d1.s:28723: Error: illegal operands `sd s7,4912(sp)'
/tmp/camlasmc5d6d1.s:28725: Error: illegal operands `sd s8,4904(sp)'
/tmp/camlasmc5d6d1.s:28727: Error: illegal operands `sd s9,4896(sp)'
/tmp/camlasmc5d6d1.s:28729: Error: illegal operands `sd t2,4888(sp)'
/tmp/camlasmc5d6d1.s:28731: Error: illegal operands `sd t3,4880(sp)'
/tmp/camlasmc5d6d1.s:28733: Error: illegal operands `sd t4,4872(sp)'
/tmp/camlasmc5d6d1.s:28735: Error: illegal operands `sd t5,4864(sp)'
/tmp/camlasmc5d6d1.s:28737: Error: illegal operands `sd t6,4856(sp)'
/tmp/camlasmc5d6d1.s:28739: Error: illegal operands `sd a1,4848(sp)'
/tmp/camlasmc5d6d1.s:28741: Error: illegal operands `sd a1,4840(sp)'
/tmp/camlasmc5d6d1.s:28743: Error: illegal operands `sd a2,4832(sp)'
/tmp/camlasmc5d6d1.s:28745: Error: illegal operands `sd a3,4824(sp)'
/tmp/camlasmc5d6d1.s:28747: Error: illegal operands `sd a4,4816(sp)'
/tmp/camlasmc5d6d1.s:28749: Error: illegal operands `sd a5,4808(sp)'
/tmp/camlasmc5d6d1.s:28751: Error: illegal operands `sd a6,4800(sp)'
/tmp/camlasmc5d6d1.s:28753: Error: illegal operands `sd a7,4792(sp)'
/tmp/camlasmc5d6d1.s:28755: Error: illegal operands `sd s2,4784(sp)'
/tmp/camlasmc5d6d1.s:28757: Error: illegal operands `sd s3,4776(sp)'
/tmp/camlasmc5d6d1.s:28759: Error: illegal operands `sd s4,4768(sp)'
/tmp/camlasmc5d6d1.s:28761: Error: illegal operands `sd s5,4760(sp)'
/tmp/camlasmc5d6d1.s:28763: Error: illegal operands `sd s6,4752(sp)'
/tmp/camlasmc5d6d1.s:28765: Error: illegal operands `sd s7,4744(sp)'
/tmp/camlasmc5d6d1.s:28767: Error: illegal operands `sd s8,4736(sp)'
/tmp/camlasmc5d6d1.s:28769: Error: illegal operands `sd s9,4728(sp)'
/tmp/camlasmc5d6d1.s:28771: Error: illegal operands `sd t2,4720(sp)'
/tmp/camlasmc5d6d1.s:28773: Error: illegal operands `sd t3,4712(sp)'
/tmp/camlasmc5d6d1.s:28775: Error: illegal operands `sd t4,4704(sp)'
/tmp/camlasmc5d6d1.s:28777: Error: illegal operands `sd t5,4696(sp)'
/tmp/camlasmc5d6d1.s:28779: Error: illegal operands `sd t6,4688(sp)'
/tmp/camlasmc5d6d1.s:28781: Error: illegal operands `sd a1,4680(sp)'
/tmp/camlasmc5d6d1.s:28783: Error: illegal operands `sd a1,4672(sp)'
/tmp/camlasmc5d6d1.s:28785: Error: illegal operands `sd a2,4664(sp)'
/tmp/camlasmc5d6d1.s:28787: Error: illegal operands `sd a3,4656(sp)'
/tmp/camlasmc5d6d1.s:28789: Error: illegal operands `sd a4,4648(sp)'
/tmp/camlasmc5d6d1.s:28791: Error: illegal operands `sd a5,4640(sp)'
/tmp/camlasmc5d6d1.s:28793: Error: illegal operands `sd a6,4632(sp)'
/tmp/camlasmc5d6d1.s:28795: Error: illegal operands `sd a7,4624(sp)'
/tmp/camlasmc5d6d1.s:28797: Error: illegal operands `sd s2,4600(sp)'
/tmp/camlasmc5d6d1.s:28799: Error: illegal operands `sd s3,4616(sp)'
```
(There are actually many many more lines, I will try to attach the assembler file and the full output shortly).

This is with the compiler from: https://git.fedorahosted.org/cgit/fedora-ocaml.git/log/?h=fedora-26-4.04.0

**Comment by nojb** [comment]
Thanks for the report!  It looks like immediates which are out of range again.  I will get it fixed ASAP.

**Comment by rwmjones** [comment]
I cannot attach large files to this bug report, but I placed various files related to the issue here:

http://oirase.annexia.org/tmp/ocaml-nojb-issue-2/

**Comment by nojb** [comment]
Great, thanks.  Will look at it shortly.

**Comment by nojb** [comment]
I just pushed a fix to `trunk` (3ba7e3e5ee92f6310ae1a36129da8d1d0b8f3402).  I am waiting for testsuite to complete and wait for your confirmation to close this.

**Comment by nojb** [comment]
Testsuite passes.

**Comment by nojb** [comment]
Apologies, the last commit was missing a crucial line: amended in 2bb213d663e16a5bab8344dc259d662d69f28065.

**Comment by rwmjones** [comment]
With the earlier version of the patch I was still getting:
```
/tmp/camlasm85af10.s: Assembler messages:
/tmp/camlasm85af10.s:28692: Error: illegal operands `sd ra,5016(sp)'
/tmp/camlasm85af10.s:42692: Error: illegal operands `ld ra,5016(sp)'
```
I will try the new version today.

**Comment by nojb** [comment]
I think I may have missed one place; I will be pushing a fix very soon.  Best to wait for it before testing again.

**Comment by nojb** [comment]
Pushed fix at 98c9e159fa65c15a57d274d53544479a436c2a40.

**Comment by rwmjones** [comment]
It now compiles libguestfs successfully.  If I find any further problems I'll open new bugs for them.  Thanks for your rapid fixes.

**Comment by nojb** [comment]
Great, thanks!
